language: java
jdk:
  - oraclejdk8
after_success:
  - mvn jacoco:prepare-agent
  - mvn jacoco:report
  - mvn -X sonar:sonar -Dsonar.jdbc.password={{sonar.jdbc.password}} -Dsonar.jdbc.url={{sonar.jdbc.url}} -Dsonar.host.url={{sonarhosturl}} -Dsonar.jdbc.username={{sonar.jdbc.username}}