language: java
jdk:
  - oraclejdk8
script:
  - mvn jacoco:prepare-agent
  - mvn jacoco:report
  - mvn -X sonar:sonar -Dsonar.jdbc.password=$sonarjdbcpassword -Dsonar.jdbc.url=$sonarjdbcurl -Dsonar.host.url=$sonarhosturl -Dsonar.jdbc.username=$sonarjdbcusername