language: java
jdk:
  - oraclejdk8
script:
  - mvn jacoco:prepare-agent
  - mvn jacoco:report
  - mvn sonar:sonar -Dsonar.jdbc.password={{sonar.jdbc.password}} -Dsonar.jdbc.url={{sonar.jdbc.url}} -Dsonar.host.url={{sonar.host.url}} -Dsonar.jdbc.username={{sonar.jdbc.username}}